// French summaries of D&D's official 2024 Basic Rules, “Choose an Alignment”.
export const ALIGNMENT_SOURCE = "https://www.dndbeyond.com/sources/dnd/br-2024/creating-a-character#Step4ChooseanAlignment";

export const ALIGNMENTS = [
  { id: "loyal-bon", name: "Loyal bon", short: "LB", summary: "Justice et devoir.", description: "Les créatures Loyales Bonnes s'efforcent de faire le bien selon les attentes de la société. Une personne qui combat l'injustice et protège les innocents sans hésiter sera probablement Loyale Bonne." },
  { id: "neutre-bon", name: "Neutre bon", short: "NB", summary: "Le bien avant les règles.", description: "Les créatures Neutres Bonnes font de leur mieux en s'adaptant aux règles, sans pour autant s'y contraindre strictement. Une personne bienveillante qui aide les autres selon leurs besoins sera probablement Neutre Bonne." },
  { id: "chaotique-bon", name: "Chaotique bon", short: "CB", summary: "Le bien en toute liberté.", description: "Les créatures Chaotiques Bonnes agissent selon ce que leur conscience leur dicte, sans se soucier des attentes de la société. Un rebelle qui intercepte les collecteurs d'impôts d'un baron cruel pour reverser l'or saisi aux indigents sera probablement Chaotique Bon." },
  { id: "loyal-neutre", name: "Loyal neutre", short: "LN", summary: "Un code avant tout.", description: "Les individus Loyaux Neutres se conduisent en accord avec la loi, les traditions ou leur code personnel. Une personne qui adhère à une discipline de vie sans se laisser influencer par les affres des nécessiteux ni les tentations du mal sera probablement Loyale Neutre." },
  { id: "neutre", name: "Neutre", short: "N", summary: "Agir selon les circonstances.", description: "L'alignement Neutre est celui des gens qui préfèrent éviter les questions morales et ne pas prendre parti, pour simplement agir au cas par cas, du mieux possible. Une personne que les débats moraux ennuient sera probablement Neutre." },
  { id: "chaotique-neutre", name: "Chaotique neutre", short: "CN", summary: "Sa liberté avant tout.", description: "Les créatures Chaotiques Neutres agissent comme bon leur semble, leur propre liberté important plus que tout le reste. Une canaille qui erre dans la nature en vivant d'expédients sera probablement Chaotique Neutre." },
  { id: "loyal-mauvais", name: "Loyal mauvais", short: "LM", summary: "L’ambition dans l’ordre.", description: "Les créatures Loyales Mauvaises s'approprient méthodiquement ce qu'elles désirent tout en restant dans le cadre de la loyauté, de la tradition ou de l'ordre. Un aristocrate qui exploite la population en intrigant pour le pouvoir sera probablement Loyal Mauvais." },
  { id: "neutre-mauvais", name: "Neutre mauvais", short: "NM", summary: "Ses intérêts sans scrupules.", description: "Neutre Mauvais est l'alignement des personnes qui n'ont cure du mal qu'elles peuvent causer pour assouvir leurs désirs. Un criminel qui vole et tue comme bon lui semble sera probablement Neutre Mauvais." },
  { id: "chaotique-mauvais", name: "Chaotique mauvais", short: "CM", summary: "Haine et destruction.", description: "La violence gratuite des créatures Chaotiques Mauvaises est motivée par la haine ou la soif de sang. Un scélérat dont les desseins sont animés par la vengeance et les ravages sera probablement Chaotique Mauvais." },
] as const;
